"use client";
import { useState } from "react";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import "../app/globals.css";

export default function RootLayout({ children }) {
  const [open, setOpen] = useState(true);

  return (
    <html lang="en">
      <body>
        <div className="layout">
          <Sidebar open={open} />
          <div className="main-content">
            <Header toggleSidebar={() => setOpen(!open)} />
            <div className="page-content">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}





// "use client"
// import "./globals.css"

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <body>{children}</body>
//       </body>
//     </html>
//   )
// }


























// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
