// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// app/layout.js
// import "./globals.css";

// export const metadata = {
//   title: "HRMS Dashboard",
//   description: "Human Resource Management System",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }



// import './globals.css';
// import Layout from '../components/Layout';

// export const metadata = {
//   title: 'HRMS Dashboard',
//   description: 'Human Resource Management System',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         {/* Wrap pages with your persistent Layout so header + sidebar remain visible */}
//         <Layout>{children}</Layout>
//       </body>
//     </html>
//   );
// }







//chatgpt

// import Sidebar from "@/components/Sidebar";
// import Header from "@/components/Header";
// import "./globals.css";

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <div className="app-container">
//           <Sidebar />
//           <div className="main-content">
//             <Header />
//             <main className="content-area">{children}</main>
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }


// src/app/layout.js
// import './globals.css';

// export const metadata = {
//   title: 'HR Management System',
//   description: 'Dashboard with Sidebar and Header',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body suppressHydrationWarning={true}>
//         {children}
//       </body>
//     </html>
//   );
// }






// src/app/layout.js
// import './globals.css';

// export const metadata = {
//   title: 'HR Management System',
//   description: 'Dashboard with Sidebar and Header',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body suppressHydrationWarning={true}>
//         {children}
//       </body>
//     </html>
//   );
// }












import "./globals.css";   // because globals.css is in the same folder
import Layout from "../components/Layout"; // Layout is outside app folder

export const metadata = {
  title: "HR Management System",
  description: "Dashboard with Sidebar and Header",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
